# Generated by Django 5.0.4 on 2024-05-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cars',
            table='lovely cars',
        ),
    ]
