# Generated by Django 5.0.4 on 2024-05-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_cars_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cars',
            table=None,
        ),
    ]
